#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  # 獲取當前的 TMUX session 名稱，如果存在的話
  current_session=$(tmux display-message -p '#S' 2>/dev/null)
  
  # 透過 grep -v 排除當前 session
  selected=$(( \
    tmux list-session -F '#S' | grep -v "^$current_session$" ; \
    zoxide query --list \
  ) | fzf --tmux --reverse)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
  tmux attach -t $selected_name
else
  tmux switch-client -t $selected_name
fi
